# -*- coding: utf-8 -*-
"""MaseengMasithaLab6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T96Raa6gzEgyv9e8TyTGY_hfygiFZ9ZA
"""

refugee_count = {"Kenya": 39526, "Yemen": 9298, "Malawi": 4950, "Sudan": 8996, "Bangladesh": 10144}

def printDictionary(dicInput):
  for (key, value) in dicInput.items():
    print(key, value)
printDictionary(refugee_count)

def printKeys(dicInput):
  for (key) in dicInput.keys():
    print (key)
print Keys(refugee_count)


def printValues(dicInput):
  for (value) in dicInput.values():
    print (value)
print Values(refugee_count)

refugee_count = {"Kenya": 39526, "Yemen": 9298, "Malawi": 4950, "Sudan": 8996, "Bangladesh": 10144}

def printDictionary(dicInput):
  for (key, value) in dicInput.items():
    print(key, value)
printDictionary(refugee_count)


def printKeys(dicInput):
  for (key) in dicInput.items():
    print (key)
printKeys(refugee_count)


def printValues(dicInput):
  for (value) in dicInput.items():
    print (values)
printValues(refugee_count)